import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "../../devlink/global.css";
import "./globals.css";
import { DevLinkProvider } from "../../devlink/DevLinkProvider";
import { HeaderAndGlobalCustomCode } from "../../devlink";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
      >
        <DevLinkProvider>
          <HeaderAndGlobalCustomCode />
          {children}
        </DevLinkProvider>
      </body>
    </html>
  );
}
